// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pacagroup.Trade.Persistence.Contexts;

#nullable disable

namespace Pacagroup.Trade.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250402154353_CreateInitialSchemeV2")]
    partial class CreateInitialSchemeV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pacagroup.Trade.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .HasPrecision(9)
                        .HasColumnType("int");

                    b.Property<DateTime>("Create")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("Quanty")
                        .HasPrecision(9)
                        .HasColumnType("int");

                    b.Property<int>("Side")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TransacTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Create = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 522.99m,
                            Quanty = 1000,
                            Side = 0,
                            Symbol = "META",
                            TransacTime = new DateTime(2025, 4, 2, 9, 50, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Create = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 424.30m,
                            Quanty = 300,
                            Side = 0,
                            Symbol = "MSFT",
                            TransacTime = new DateTime(2025, 4, 2, 9, 50, 0, 0, DateTimeKind.Unspecified),
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Create = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0m,
                            Quanty = 400,
                            Side = 1,
                            Symbol = "AMZN",
                            TransacTime = new DateTime(2025, 4, 2, 9, 50, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Create = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 0m,
                            Quanty = 800,
                            Side = 1,
                            Symbol = "TSLA",
                            TransacTime = new DateTime(2025, 4, 2, 9, 50, 0, 0, DateTimeKind.Unspecified),
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
